# -*- coding: utf-8 -*-
"""ahmetKaya.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N45D_fj_cJQUBulscOfGvDfNpKFPuxAu

**Install Required Libraries**
"""

!pip install spotipy beautifulsoup4 requests

"""
**Getting Ahmet Kaya's Songs with Spotify API**"""

import requests
import csv
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from bs4 import BeautifulSoup

# Spotify API
client_id = "175c889a7f694e9b8447d48d1f0253df"
client_secret = "83bf4b142ec04d3fafcc51e296ef459b"

sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(client_id=client_id, client_secret=client_secret))

artist_id = "1Y2FwScblyMxpLTrNdfwyU"

# I got the popular songs of the week of spotify
def get_top_songs():
    results = sp.artist_top_tracks(artist_id)
    top_songs = []
    for track in results['tracks'][:5]:
        song_name = track['name']
        song_url = track['external_urls']['spotify']
        song_popularity = track['popularity']
        top_songs.append({'name': song_name, 'url': song_url, 'popularity': song_popularity})

    return top_songs

# Here I clean the Song names because it should match the data I scraped from the other site
def clean_song_name(song_name):
    if song_name.startswith("Ahmet Kaya - "):
        return song_name.replace("Ahmet Kaya - ", "").strip()
    return song_name.strip()


# Main URL
base_url = "https://sarki.alternatifim.com/sarkici/ahmet-kaya?sayfa="


spotify_songs = get_top_songs()

# Create CSV file and add headers
with open('ahmet_kaya.csv', 'w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Popularity', 'Song Name', 'Lyrics', 'Spotify URI'])


    # We visit the site from which we extract data
    sayfa_no = 1
    while True:
        url = base_url + str(sayfa_no)
        print(f"İşleniyor: {url}")

        response = requests.get(url)
        if response.status_code != 200:
            print("Bağlantı başarısız veya sayfa yok:", response.status_code)
            break

        soup = BeautifulSoup(response.text, 'html.parser')
        song_links = soup.find_all('a', href=True)
        song_urls = ['https://sarki.alternatifim.com' + link['href'] for link in song_links if "/sarkici/ahmet-kaya/" in link['href']]

        if not song_urls:
            print("All songs taken")
            break

        # We browse song pages and save lyrics to CSV
        for song_url in song_urls:
            song_response = requests.get(song_url)
            song_soup = BeautifulSoup(song_response.text, 'html.parser')


            song_name = song_soup.find('h1', class_='baslik')
            if song_name:
                song_name = song_name.text.strip()
                song_name = clean_song_name(song_name)
            else:
                song_name = "Unknown"


            if any(song['name'] == song_name for song in spotify_songs):

                lyrics = song_soup.find('div', class_='sarkisozu')
                if lyrics:
                    lyrics_text = lyrics.text.strip()
                else:
                    lyrics_text = "No lyrics found"


                spotify_uri = next((song['url'] for song in spotify_songs if song['name'] == song_name), "Spotify URI bulunamadı")


                song_popularity = next((song['popularity'] for song in spotify_songs if song['name'] == song_name), 0)


                writer.writerow([song_popularity, song_name, lyrics_text, spotify_uri])

        sayfa_no += 1

print("Haftanın popüler 5 şarkısı ve sözleri başarıyla kaydedildi: ahmet_kaya.csv")

"""**Sending Email with SMTP**"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import os

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

EMAIL_ADDRESS = "sesly.app@gmail.com"
EMAIL_PASSWORD = "rvax etzo bets vnjo"
TO_EMAIL = "yusufbatkitar34@gmail.com"

csv_filename = 'ahmet_kaya.csv'

# Email sending function
def send_email():
    msg = MIMEMultipart()
    msg["From"] = EMAIL_ADDRESS
    msg["To"] = TO_EMAIL
    msg["Subject"] = "Top 5 Ahmet Kaya Songs of the Week"

    # Here we add text to the email
    email_body = "Top 5 Ahmet Kaya Songs of the Week"
    msg.attach(MIMEText(email_body, "plain"))

    # Here we add your csv file
    file = open(csv_filename, "rb")
    attachment = MIMEBase("application", "octet-stream")
    attachment.set_payload(file.read())
    encoders.encode_base64(attachment)
    attachment.add_header("Content-Disposition", f"attachment; filename={os.path.basename(csv_filename)}")
    msg.attach(attachment)

    # We connect to the SMTP server and send the email
    server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
    server.starttls()
    server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
    server.sendmail(EMAIL_ADDRESS, TO_EMAIL, msg.as_string())
    server.quit()

send_email()